times/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from models import Time


class NovoTimeForm(FlaskForm):

    nome_time = StringField('Nome do Time',
                            validators=[DataRequired(), Length(min=3, max=50)])
    escudo = StringField('Link Escudo')
    enviar = SubmitField('enviar')

    def __init__(self, nome_original=None, *args, **kwargs):
        super(NovoTimeForm, self).__init__(*args, **kwargs)
        self.nome_original = nome_original

    def validate_nome_time(self, nome_time):
        if self.nome_original is None or \
           self.nome_original != self.nome_time.data:
            time = Time.query.filter_by(nome=nome_time.data).first()
            if time is not None:
                raise ValidationError('Esse time já existe')

times/__init__.py
from flask import Blueprint

bp = Blueprint('times', __name__, template_folder='templates')

from times import routes

times/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required
from times import bp
from times.forms import NovoTimeForm
from models import Time
from brasileirao import db


@bp.route('/')
@login_required
def index():
    times = Time.query.order_by(Time.nome).all()
    return render_template('listar.html', title='Times', times=times)


@bp.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    form = NovoTimeForm()
    if form.validate_on_submit():
        time = Time(nome=form.nome_time.data, escudo=form.escudo.data)
        db.session.add(time)
        db.session.commit()
        return redirect(url_for('times.index'))
    return render_template('novotime.html', title='Novo Time', form=form)

@bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def update(id):

    time = Time.query.get_or_404(id)
    form = NovoTimeForm(nome_original=time.nome)
    if form.validate_on_submit():
        time.nome = form.nome_time.data
        time.escudo = form.escudo.data
        db.session.add(time)
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('times.index'))
    elif request.method == 'GET':
        time = Time.query.get(id)
        form.nome_time.data = time.nome
        form.escudo.data = time.escudo
    return render_template('novotime.html', form=form, title='Editar Time')


@bp.route('/<int:id>/delete')
@login_required
def delete(id):
    time = Time.query.get_or_404(id)
    db.session.delete(time)
    db.session.commit()
    return redirect(url_for('times.index'))

times/templates/listar.html
{% extends "base.html"%}

{% block app_content %}
<h1>Times</h1>
<a href="{{ url_for('times.create') }}" class="btn btn-primary">Novo time</a>
<br>
<br>
<div class="container">
	<ul class="list-unstyled row">
		{% for time in times %}
		 <li class="list-group-item col-md-4 borderless text-center">
			<h4>
			<img class="escudo-mini" src="{{ time.escudo }}"> 
			{{ time.nome }}
			</h4>
             <a class="btn btn-warning" href="{{ url_for('times.update', id=time.id) }}">Editar</a>
			 <a class="btn btn-danger" href="{{ url_for('times.delete', id=time.id) }}">Apagar</a>
		 </li>
		{% endfor %}
	</ul>
</div>
{% endblock %} 

times/templates/novotime.html
{% extends "base.html" %}

{% block app_content %}
<h1> {{ title }}</h1>

<form action="" method="POST" novalidate>
	{{ form.hidden_tag() }}
	<div class="container">
	<div class="row">
		<div class="col-md-4">
			{{ form.nome_time.label }} {{ form.nome_time(size=32) }}
			{{ form.escudo.label }} {{ form.escudo(size=32) }}
			{{ form.enviar() }}
		</div>
	</div>
</div>
</form>

{% endblock %}