jogos/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, IntegerField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, ValidationError


class NovoJogoForm(FlaskForm):

    rodada = IntegerField('Rodada', validators=[DataRequired()])
    data = DateField('Data da Partida')
    vermelhos_mandante = IntegerField('Vermelhos', default=0)
    mandante = SelectField('Time Mandante', coerce=int)
    gols_mandante = IntegerField('Gols')
    amarelos_mandante = IntegerField('Amarelos', default=0)
    vermelhos_mandante = IntegerField('Vermelhos', default=0)
    visitante = SelectField('Time Visitante', coerce=int)
    gols_visitante = IntegerField('Gol')
    amarelos_visitante = IntegerField('Amarelos', default=0)
    vermelhos_visitante = IntegerField('Vermelhos', default=0)
    enviar = SubmitField('Salvar')
    atualizar = SubmitField('Atualizar')

    def validate_visitante(self, visitante):
        if visitante.data == self.mandante.data:
            raise ValidationError('O Time mandante e o Visitante não podem'
                                  'ser o mesmo')

    def validate_rodada(self, rodada):
        if rodada.data > 10 or rodada.data < 0:
            raise ValidationError('Rodada Inválida')

jogos/__init__.py
from flask import Blueprint

bp = Blueprint('jogos', __name__, template_folder='./templates')

from jogos import routes

jogos/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required
from jogos import bp
from jogos.forms import NovoJogoForm
from models import Jogo, Time
from brasileirao import db
from sqlalchemy.exc import IntegrityError


@bp.route('/')
@login_required
def index():
    jogos = Jogo.jogos_rodada()
    return render_template('listarjogos.html', title='Jogos', jogos=jogos)


@bp.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    form = NovoJogoForm()
    times = list(Time.query.with_entities(Time.id, Time.nome))
    escudos = list(Time.query.with_entities(Time.nome, Time.escudo))
    form.mandante.choices = times
    form.visitante.choices = times
    if form.validate_on_submit():
        jogo = Jogo(rodada=form.rodada.data, data=form.data.data,
                    time_mandante_id=form.mandante.data,
                    gols_mandante=form.gols_mandante.data,
                    amarelos_mandante=form.amarelos_mandante.data,
                    vermelhos_mandante=form.vermelhos_mandante.data,
                    time_visitante_id=form.visitante.data,
                    gols_visitante=form.gols_visitante.data,
                    amarelos_visitante=form.amarelos_visitante.data,
                    vermelhos_visitante=form.vermelhos_visitante.data)
        try:
            db.session.add(jogo)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            e = {'Duplicidade': ["Esta partida já ocorrreu"]}
            return render_template('novojogo.html', title='Novo Jogo',
                                   form=form, times=times, escudos=escudos, jogo=None, errors=e)
        else:
            flash('Jogo criado com sucesso.')
            return redirect(url_for('jogos.index'))
    return render_template('novojogo.html', title='Novo Jogo', form=form,
                           jogo=None, times=times, escudos=escudos, errors=form.errors)


@bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def update(id):
    jogo = Jogo.query.get_or_404(id)
    form = NovoJogoForm()
    times = list(Time.query.with_entities(Time.id, Time.nome))
    escudos = list(Time.query.with_entities(Time.nome, Time.escudo))
    form.mandante.choices = times
    form.visitante.choices = times
    if form.validate_on_submit():
        jogo.rodada = form.rodada.data
        jogo.data = form.data.data
        jogo.time_mandante_id = form.mandante.data
        jogo.gols_mandante = form.gols_mandante.data
        jogo.amarelos_mandante = form.amarelos_mandante.data
        jogo.vermelhos_mandante = form.vermelhos_mandante.data
        jogo.time_visitante_id = form.visitante.data
        jogo.gols_visitante = form.gols_visitante.data
        jogo.amarelos_visitante = form.amarelos_visitante.data
        jogo.vermelhos_visitante = form.vermelhos_visitante.data
        db.session.add(jogo)
        db.session.commit()
        flash('Jogo alterado com sucesso.')
        return redirect(url_for('jogos.index'))
    elif request.method == 'GET':
        form.rodada.data = jogo.rodada
        form.data.data = jogo.data
        form.mandante.data = jogo.time_mandante_id
        form.gols_mandante.data = jogo.gols_mandante
        form.amarelos_mandante.data = jogo.amarelos_mandante
        form.vermelhos_mandante.data = jogo.vermelhos_mandante
        form.visitante.data = jogo.time_visitante_id
        form.gols_visitante.data = jogo.gols_visitante
        form.amarelos_visitante.data = jogo.amarelos_visitante
        form.vermelhos_visitante.data = jogo.vermelhos_visitante
    return render_template('novojogo.html', form=form, title="Editar Jogo",
                           jogo=jogo, escudos=escudos, errors=form.errors)


@bp.route('/<int:id>/delete')
@login_required
def delete(id):
    jogo = Jogo.query.get_or_404(id)
    db.session.delete(jogo)
    db.session.commit()
    flash('Jogo apagado com sucesso.')
    return redirect(url_for('jogos.index'))

jogos/templates/listarjogos.html
{% extends "base.html"%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
	{{ super() }}
	<style>
	body {
		width: 100%;
		margin: 0;
		padding: 0;
	}
    a{
		color: black;
	}
    a:hover, a:focus {
    text-decoration: none;
}
	</style>
{% endblock %}
{% block app_content %}

<h1>Jogos</h1>
<a href="{{url_for('jogos.create')}}" class="btn btn-primary">Novo jogo</a>
<br>
<br>
{% for rodada in jogos %}
<h1 class="center"><a data-toggle="collapse" href="#collapseJogo{{ rodada }}">
    Rodada {{ rodada }}
  </a></h1>
    <div class="container">
        <ul class="list-unstyled row collapse" id="collapseJogo{{ rodada }}">
        {% for jogo in jogos[rodada] %}

        <a href="{{ url_for('jogos.update', id=jogo.id)}}">
            <div>
            <li class="list-group-item col-md-4 borderless text-center">
                <img class="escudo-mini" src="{{jogo.mandante.escudo}}">
                    {{ jogo.mandante.nome }}
                    {{ jogo.gols_mandante }} x
                    {{ jogo.gols_visitante}}
                    {{ jogo.visitante.nome}}
                <img class="escudo-mini" src="{{jogo.visitante.escudo}}">
                
            </li>
            </div>
        </a>

        {% endfor %}
        </ul>
    </div>

{% endfor %}
{% endblock %}

jogos/templates/novojogo.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
	{{ super() }}
	<style>
	body {
		width: 100%;
		margin: 0;
		padding: 0;
	}
	#form-jogos .row {
		font-size: 15pt;
		padding: 10px;
	}
	#form-jogos #escudos-times {
		font-size: 28pt;
	}
	</style>
{% endblock %}

{% block app_content %}
<!-- Esse bloco é um gerenciamento de Erro, não precisa mexer -->
{% if errors %}
	<div class="container">
    	{%- for msg in errors %}
    		<div class="alert alert-danger" role="alert">
				{{ msg }}
				{% for error in errors[msg] %}
				{{error}}
				{% endfor %}
			</div>
    	{% endfor -%}
	</div>
{% endif %}

<!-- Faça o template a partir daqui-->
<h1> {{ title }}</h1>

<form id="form-jogos" action="" method="POST" novalidate>
	{{ form.hidden_tag() }}
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="col col-md-4">
				<div class="row text-center">
				{{ form.mandante }}
				</div>
				<div class="row text-center">
					Cartões:
					<img src="{{url_for('static', filename='images/amarelo.png')}}" style="height: 30px;"/>
					{{ form.amarelos_mandante(size=2, class="text-center") }}
					<img src="{{url_for('static', filename='images/vermelho.png')}}" style="height: 30px;"/>
					{{ form.vermelhos_mandante(size=2, class="text-center") }}	
				</div>
			</div>
			<div id="escudos-times" class="col col-md-4 text-center">
				<img id="escudo-mandante" class="escudo-mini" src="#"> 
				{{ form.gols_mandante(size=2, class="text-center") }}
				<span>X</span>
				{{ form.gols_visitante(size=2, class="text-center") }}
				<img id="escudo-visitante" class="escudo-mini" src="#"> 
			</div>
			<div class="col col-md-4">
				<div class="row text-center">
				{{ form.visitante }}
				</div>
				<div class="row text-center">
					Cartões:
					<img src="{{url_for('static', filename='images/amarelo.png')}}" style="height: 30px;"/>
					{{ form.amarelos_visitante(size=2, class="text-center") }}
					<img src="{{url_for('static', filename='images/vermelho.png')}}" style="height: 30px;"/>
					{{ form.vermelhos_visitante(size=2, class="text-center") }}
				</div>
			</div>	
		</div>
		<div class="row">
			<div class="col col-md-4 text-center">
				{{ form.rodada.label }} {{ form.rodada(size=2, class="text-center") }}
			</div>
			<div class="col col-md-4 text-center">
					{{ form.data.label }} {{ form.data(class="text-center") }}
			</div>
			<div class="col col-md-4 text-center">
					{% if title=='Novo Jogo' %}
					{{ wtf.form_field(form.enviar, class="btn btn-success", button_map={'submit': 'primary'}) }}
					{% else %}
					{{ wtf.form_field(form.atualizar, class="btn btn-success", button_map={'submit': 'primary'}) }}
					<a class="btn btn-danger" href="{{ url_for('jogos.delete', id=jogo.id) }}">Apagar</a>
					{% endif %}
			</div>
		</div>
	</div>
</form>

{% endblock %}



{% block scripts %}
    {{ super() }}
    <script>
		let escudos = {{escudos|tojson}}
			$(document).ready(() => {
				let time = $("#mandante option:selected").text();
				escudos.forEach(element => {
					if (time == element[0]) {
						$('#escudo-mandante').attr('src', element[1])
					}
				})
				time = $("#visitante option:selected").text();
				escudos.forEach(element => {
					if (time == element[0]) {
						$('#escudo-visitante').attr('src', element[1])
					}
				})
			})
			$('#mandante').change(() => {
				let time = $("#mandante option:selected").text();
				escudos.forEach(element => {
					if (time == element[0]) {
						$('#escudo-mandante').attr('src', element[1])
					}
				})
			})
			$('#visitante').change(() => {
				let time = $("#visitante option:selected").text();
				escudos.forEach(element => {
					if (time == element[0]) {
						$('#escudo-visitante').attr('src', element[1])
					}
				})
			})
		</script>
{% endblock %}